import { Geist, Geist_Mono } from "next/font/google";
import { allFontVariables } from "./fonts";
import '@/app/globals.css'



export const metadata = {
  title: "Create Next Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${allFontVariables} antialiased`}>
        {children}
      </body>
    </html>
  );
}
